routes:
  - protocol: "http"
    host: "host.docker.internal"
    path: "/header"
    StripPath: true
    service: "meu-nginx"
    port: 8081
    ttl: 10
    retry: 3
    retryDelay: 5
    healthPath: /
    cors:
      allowedOrigins:
        - "http://host.docker.internal:9000"
      allowedMethods:
        - "GET"
cors:
  allowedOrigins:
    - "*"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowedHeaders:
    - "Authorization"
    - "Content-Type"
  allowCredentials: true
  exposedHeaders:
    - "X-Custom-Header"
  maxAge: 3600