version: '3.9'

services:
  api-gateway-knative-docker-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: caiomarcatti12/api-gateway-knative-docker:prod
    container_name: api-gateway-knative-docker
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

